version: '3.7'

services:

  prometheus:
    image: prom/prometheus:v2.8.1
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    links:
      - exporter

  exporter:
    build:
      context: ./
      dockerfile: ./docker/exporter/Dockerfile
    ports:
      - 9259:9259
    links:
      - testservice

  testservice:
    build:
      context: ./docker/testservice
    expose:
      - 8081
    ports:
      - 8081:8081

volumes:
  prometheus_data: {}
