version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12.1-stretch
    steps:
      - checkout
      - run: make test
  build:
    machine: true
    steps:
      - checkout
      - run: make build
      - run:
          name: Archive Docker image
          command: docker save -o image.tar cs_exporter
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  deploy:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Build and push Docker image to quay.io
          command: |
            IMAGE_TAG="0.0.${CIRCLE_BUILD_NUM}"
            docker tag cs_exporter ${QUAY_LOGIN}/cs_exporter:${IMAGE_TAG}
            docker tag cs_exporter ${QUAY_LOGIN}/cs_exporter:latest
            docker login -u ${QUAY_LOGIN} -p ${QUAY_PASSWORD} quay.io
            docker push ${QUAY_LOGIN}/cs_exporter:${IMAGE_TAG}
            docker push ${QUAY_LOGIN}/cs_exporter:latest

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: master
