version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12.1-stretch
    steps:
      - checkout
      - run: make test 
  build:
    docker:
      - image: circleci/golang:1.12.1-stretch
    steps:
      - checkout
      - run: make build 
workflows:
  version: 2
  test_and_build:
    jobs:
      - test 
      - build
